name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'prod'
        type: choice
        options:
        - dev
        - stage
        - prod

jobs:
  test:
    name: Run tests on ${{ github.event.inputs.environment || 'prod' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: Dake

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Debug environment variables
      run: |
        echo "Environment: ${{ github.event.inputs.environment || 'prod' }}"
        echo "BASE_URL will be: ${{ secrets[format('BASE_URL_{0}', github.event.inputs.environment || 'PROD')] }}"

    - name: Run Playwright tests
      run: |
        mkdir -p test-results
        echo "Current BASE_URL value: $BASE_URL"
        npx playwright test tests/example.spec.js --reporter=list,html | tee test-results/running-log.txt
      env:
        BASE_URL: ${{ github.event.inputs.environment == 'dev' && secrets.BASE_URL_DEV || github.event.inputs.environment == 'stage' && secrets.BASE_URL_STAGE || secrets.BASE_URL_PROD }}

    - name: Save logs
      if: always()
      run: |
        mkdir -p logs
        echo "Test execution log:" > logs/test.log
        echo "Environment: ${{ github.event.inputs.environment }}" >> logs/test.log
        npx playwright test tests/example.spec.js --reporter=list >> logs/test.log 2>&1

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: logs/
        retention-days: 30

    - name: Upload running log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: running-log
        path: test-results/running-log.txt

  deploy-report:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_TOKEN }}
          fetch-depth: 0
      
      - name: Download playwright report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: docs/playwright-report
          
      - name: Commit and push report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin main
          git reset --hard origin/main
          git add -f docs/playwright-report
          git commit -m "Update Playwright report" || echo "No changes to commit"
          git push origin main
        